/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExperienceLevel = { 'mid' : null } |
  { 'junior' : null } |
  { 'lead' : null } |
  { 'senior' : null } |
  { 'fresher' : null };
export interface InterviewSession {
  'id' : SessionId,
  'name' : string,
  'createdAt' : Timestamp,
  'qaPairs' : Array<QAPair>,
}
export interface QAPair {
  'id' : QAPairId,
  'question' : string,
  'answer' : string,
  'timestamp' : Timestamp,
}
export type QAPairId = bigint;
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type SessionId = bigint;
export interface SessionSummary {
  'id' : SessionId,
  'qaCount' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
}
export type Timestamp = bigint;
export interface UserProfile {
  'age' : [] | [bigint],
  'experienceLevel' : [] | [ExperienceLevel],
  'preferredLanguage' : [] | [string],
  'name' : string,
  'education' : [] | [string],
  'degree' : [] | [string],
  'targetRole' : [] | [string],
  'targetCompany' : [] | [string],
  'skills' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__openAIKeys' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, string]>
  >,
  '__qaCounter' : ActorMethod<[], any>,
  '__sessionCounter' : ActorMethod<[], any>,
  '__sessions' : ActorMethod<[], any>,
  '__userProfiles' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserProfile]>
  >,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addQAPairToSession' : ActorMethod<
    [SessionId, string, string],
    [] | [QAPair]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearMyOpenAIApiKey' : ActorMethod<[], undefined>,
  'createInterviewSession' : ActorMethod<[string], InterviewSession>,
  'deleteInterviewSession' : ActorMethod<[SessionId], boolean>,
  'generateInterviewAnswer' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInterviewSession' : ActorMethod<[SessionId], [] | [InterviewSession]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMyOpenAIConfigured' : ActorMethod<[], boolean>,
  'listInterviewSessions' : ActorMethod<[], Array<SessionSummary>>,
  'regenerateInterviewAnswer' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMyOpenAIApiKey' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];