/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExperienceLevel = IDL.Variant({
  'mid' : IDL.Null,
  'junior' : IDL.Null,
  'lead' : IDL.Null,
  'senior' : IDL.Null,
  'fresher' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'experienceLevel' : IDL.Opt(ExperienceLevel),
  'preferredLanguage' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'education' : IDL.Opt(IDL.Text),
  'degree' : IDL.Opt(IDL.Text),
  'targetRole' : IDL.Opt(IDL.Text),
  'targetCompany' : IDL.Opt(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const SessionId = IDL.Nat;
export const QAPairId = IDL.Nat;
export const Timestamp = IDL.Nat;
export const QAPair = IDL.Record({
  'id' : QAPairId,
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'timestamp' : Timestamp,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InterviewSession = IDL.Record({
  'id' : SessionId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'qaPairs' : IDL.Vec(QAPair),
});
export const SessionSummary = IDL.Record({
  'id' : SessionId,
  'qaCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__openAIKeys' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  '__qaCounter' : IDL.Func([], [IDL.Reserved], ['query']),
  '__sessionCounter' : IDL.Func([], [IDL.Reserved], ['query']),
  '__sessions' : IDL.Func([], [IDL.Reserved], ['query']),
  '__userProfiles' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addQAPairToSession' : IDL.Func(
      [SessionId, IDL.Text, IDL.Text],
      [IDL.Opt(QAPair)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearMyOpenAIApiKey' : IDL.Func([], [], []),
  'createInterviewSession' : IDL.Func([IDL.Text], [InterviewSession], []),
  'deleteInterviewSession' : IDL.Func([SessionId], [IDL.Bool], []),
  'generateInterviewAnswer' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInterviewSession' : IDL.Func(
      [SessionId],
      [IDL.Opt(InterviewSession)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listInterviewSessions' : IDL.Func([], [IDL.Vec(SessionSummary)], ['query']),
  'regenerateInterviewAnswer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMyOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExperienceLevel = IDL.Variant({
    'mid' : IDL.Null,
    'junior' : IDL.Null,
    'lead' : IDL.Null,
    'senior' : IDL.Null,
    'fresher' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'experienceLevel' : IDL.Opt(ExperienceLevel),
    'preferredLanguage' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'education' : IDL.Opt(IDL.Text),
    'degree' : IDL.Opt(IDL.Text),
    'targetRole' : IDL.Opt(IDL.Text),
    'targetCompany' : IDL.Opt(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const SessionId = IDL.Nat;
  const QAPairId = IDL.Nat;
  const Timestamp = IDL.Nat;
  const QAPair = IDL.Record({
    'id' : QAPairId,
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InterviewSession = IDL.Record({
    'id' : SessionId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'qaPairs' : IDL.Vec(QAPair),
  });
  const SessionSummary = IDL.Record({
    'id' : SessionId,
    'qaCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__openAIKeys' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    '__qaCounter' : IDL.Func([], [IDL.Reserved], ['query']),
    '__sessionCounter' : IDL.Func([], [IDL.Reserved], ['query']),
    '__sessions' : IDL.Func([], [IDL.Reserved], ['query']),
    '__userProfiles' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addQAPairToSession' : IDL.Func(
        [SessionId, IDL.Text, IDL.Text],
        [IDL.Opt(QAPair)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearMyOpenAIApiKey' : IDL.Func([], [], []),
    'createInterviewSession' : IDL.Func([IDL.Text], [InterviewSession], []),
    'deleteInterviewSession' : IDL.Func([SessionId], [IDL.Bool], []),
    'generateInterviewAnswer' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInterviewSession' : IDL.Func(
        [SessionId],
        [IDL.Opt(InterviewSession)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listInterviewSessions' : IDL.Func(
        [],
        [IDL.Vec(SessionSummary)],
        ['query'],
      ),
    'regenerateInterviewAnswer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMyOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };